const GAME_STATUS = {
    WAITING: "WAITING",
    ROUND_TIMER: "ROUND_TIMER",
    CHECK_TURN: "CHECK_TURN",
    PLAYING: "PLAYING",
    WINNER: "WINNER",
    LOCK_TABLE: "LOCK_TABLE",
}
export { GAME_STATUS }