const QUEUE_EVENT = {
    JOIN_BOT: 'JOIN_BOT',
    ROUND_TIMER: 'ROUND_TIMER',
    LOCK_TABLE: 'LOCK_TABLE',
    RE_START: "RE_START",
    DELETE_TABLE: "DELETE_TABLE",
    BOT_PLAY: "BOT_PLAY",
}

export { QUEUE_EVENT }