const SOCKET_EVENT_NAME = {
    POP_UP: 'POP_UP',
    SIGN_UP: 'SIGN_UP',
    JOIN_TABLE: "JOIN_TABLE",
    ROUND_TIMER: 'ROUND_TIMER',
    LOCK_TABLE: 'LOCK_TABLE',
    TURN: 'TURN',
    PLAY: "PLAY",
    SEND_PLACE: "SEND_PLACE",
    MOVE: "MOVE",
    CHANGE_TURN: "CHANGE_TURN",
    KING: "KING",
}

export { SOCKET_EVENT_NAME }