const SOCKET_EVENT_NAME = {
    POP_UP: 'POP_UP',
    SIGN_UP: 'SIGN_UP',
    JOIN_TABLE: "JOIN_TABLE",
    ROUND_TIMER: 'ROUND_TIMER',
    LOCK_TABLE: 'LOCK_TABLE',
    TURN: 'TURN',
    PLAY: "PLAY",
}

export { SOCKET_EVENT_NAME }